plugin: aws_ec2
regions:
  - "us-east-1"
filters:
  tag:Project: Devops-Project-Server #terraformda tagi Devops-Project-Server olan sunucuları filtreler
keyed_groups:
  - key: tags.Name #Bu makineleri terraform kalkan her ortam için gruplamasını sağlar
compose:
  ansible_host: public_ip_address #public ip adreslerini compose etmeye işe yarar